

UNAME := $(shell uname)

ifeq ($(shell uname -o 2>/dev/null),Msys)
	OS := MINGW
endif

ifneq ("$(OS)","")
	EZ_PATH=../../
endif

rosalindLIB_PATH=$(EZ_PATH)/libeasea/

CXXFLAGS =  -fopenmp	-O2 -g -Wall -fmessage-length=0 -I$(rosalindLIB_PATH)include -I$(EZ_PATH)boost -I/usr/local/opt/llvm/include

OBJS = rosalind.o rosalindIndividual.o 

LIBS = -lpthread -fopenmp 
ifneq ("$(OS)","")
	LIBS += -lws2_32 -lwinmm -L"C:\MinGW\lib"
endif

#USER MAKEFILE OPTIONS :

CXXFLAGS+=-std=c++11

#END OF USER MAKEFILE OPTIONS

TARGET =	rosalind

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LDFLAGS) -L/usr/local/opt/llvm/lib -g $(rosalindLIB_PATH)/libeasea.a $(EZ_PATH)boost/program_options.a $(LIBS)

	
#%.o:%.cpp
#	$(CXX) -c $(CXXFLAGS) $^

all:	$(TARGET)
clean:
ifneq ("$(OS)","")
	-del $(OBJS) $(TARGET).exe
else
	rm -f $(OBJS) $(TARGET)
endif
easeaclean:
ifneq ("$(OS)","")
	-del $(TARGET).exe *.o *.cpp *.hpp rosalind.png rosalind.dat rosalind.prm rosalind.mak Makefile rosalind.vcproj rosalind.csv rosalind.r rosalind.plot rosalind.pop
else
	rm -f $(TARGET) *.o *.cpp *.hpp rosalind.png rosalind.dat rosalind.prm rosalind.mak Makefile rosalind.vcproj rosalind.csv rosalind.r rosalind.plot rosalind.pop
endif

